#!/usr/bin/env bash

set -e

cd utils

rm -f CMakeCache.txt

cmake -D CMAKE_INSTALL_PREFIX=$1 \
-D CMAKE_CXX_COMPILER="$LCRCXX" \
-D CMAKE_CXX_FLAGS:STRING="$LCRCXXFLAGS" \
-D CMAKE_C_COMPILER="$LCRCC" \
-D CMAKE_C_FLAGS:STRING="$LCRCFLAGS" \
-D CMAKE_VERBOSE_MAKEFILE=ON \
-D GDAL_INCLUDE_DIR=$GDAL_INCLUDE_PATH \
-D GDAL_LIB_PATH=$GDAL_LIB_PATH \
-D GEOS_INCLUDE_DIR=$GEOS_INCLUDE_PATH \
-D GEOS_LIB_PATH=$GEOS_LIB_PATH \
.

make 
make install

cd ../gdalaoi

rm -f CMakeCache.txt

cmake -D CMAKE_INSTALL_PREFIX=$1 \
-D CMAKE_CXX_COMPILER="$LCRCXX" \
-D CMAKE_CXX_FLAGS:STRING="$LCRCXXFLAGS" \
-D CMAKE_C_COMPILER="$LCRCC" \
-D CMAKE_C_FLAGS:STRING="$LCRCFLAGS" \
-D CMAKE_VERBOSE_MAKEFILE=ON \
-D GDAL_INCLUDE_DIR=$GDAL_INCLUDE_PATH \
-D GDAL_LIB_PATH=$GDAL_LIB_PATH \
-D GDAL_SRC_PATH=$GDAL_SRC_PATH \
.

make 
make install

cd ..
